// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using examCreator.Models.Data;

#nullable disable

namespace examCreator.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220504072206_AdminUserSeedingToApplicationUser")]
    partial class AdminUserSeedingToApplicationUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("examCreator.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("LoggedInSecret")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("ApplicationUser");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("ea5ae113-c88e-4b4b-a7b2-dae9d34840aa"),
                            Password = "Temp1234*",
                            UserName = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
